name: Build and Release

on:
  push:
    tags: [ v* ]
  workflow_dispatch:

run-name: Build and Release ${{ github.ref_name }}

defaults:
  run:
    shell: bash

jobs:
  build_matrix:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gbdev/rgbds:v1.0.1
    strategy:
      fail-fast: true
      matrix:
        include:
          - repo: pret
            ref: master
          - repo: fp555
            ref: ${{ github.ref_name }}
    outputs:
      pret_id: ${{ steps.artifact_pret.outputs.artifact-id }}
      fp555_id: ${{ steps.artifact_fp555.outputs.artifact-id }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          repository: ${{ matrix.repo }}/pokecrystal
          ref: ${{ matrix.ref }}
      - name: Make ROM
        id: make
        run: |
          echo "::group::Make"
          make -j$(nproc)
          echo "::endgroup::"
          sha1sum pokecrystal.gbc | tee >(echo "hash_${{ matrix.repo }}=$(grep -o '^[^ ]*')" >> $GITHUB_OUTPUT)
      - name: Check SHA1
        if: matrix.repo == 'pret'
        env:
          BASEROM_SHA: f4cd194bdee0d04ca4eac29e09b8e4e9d818c133
        run: |
            if [[ ${{ steps.make.outputs.hash_pret }} != $BASEROM_SHA ]]; then
            echo "::warning::SHA1 mismatch for ${{ matrix.repo }}/pokecrystal.gbc: expected $BASEROM_SHA, got ${{ steps.make.outputs.hash_pret }}"
            else
            echo "${{ matrix.repo }}/pokecrystal.gbc: SHA1 OK"
            fi
      - name: ROM free space
        if: matrix.repo == 'fp555'
        run: |
          echo "# Job Summary for ${{ matrix.ref }}" >> $GITHUB_STEP_SUMMARY
          echo "Built ROM with SHA1: ${{ steps.make.outputs.hash_fp555 }}" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          python3 .github/free_space.py pokecrystal.map BANK=all | tee >(tail -n 1 >> "$GITHUB_STEP_SUMMARY")
      - name: Upload ROM
        id: artifact_pret
        if: matrix.repo == 'pret'
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.repo }}
          path: pokecrystal.gbc
          if-no-files-found: error
      - name: Upload ROM
        id: artifact_fp555
        if: matrix.repo == 'fp555'
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.repo }}
          path: pokecrystal.gbc
          if-no-files-found: error
      - name: Upload debug files
        if: matrix.repo == 'fp555'
        uses: actions/upload-artifact@v6
        with:
          name: debug_${{ matrix.ref }}
          path: |
            pokecrystal.map
            pokecrystal.sym
          if-no-files-found: error
    
  patch_release:
    runs-on: ubuntu-latest
    needs: build_matrix
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{ needs.build_matrix.outputs.pret_id }},${{ needs.build_matrix.outputs.fp555_id }}
      - name: Download Flips
        uses: robinraju/release-downloader@v1
        with:
          repository: Alcaro/Flips
          latest: true
          filename: flips-linux.zip
          extract: true
      - name: Create BPS patch
        run: |
          chmod +x flips
          ./flips --create --bps pret/pokecrystal.gbc fp555/pokecrystal.gbc patch_${{ github.ref_name }}.bps
      - name: Create release draft
        if: github.ref_type == 'tag'
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          draft: true
          prerelease: true
          artifacts: '*.bps'
          artifactErrorsFailBuild: true
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: patch
          path: '*.bps'
          if-no-files-found: error
      - name: Remove GBC artifacts
        uses: geekyeggo/delete-artifact@v6
        with:
          name: |
            fp555
            pret
          failOnError: false
